### ISSUE TITLE
Crash when Network is unreachable (wifi-off)

### ISSUE THREAD

**Issue by YanMESS** [flowsprenger/RxLifx-Kotlin#5]
Hi,
Thanks for this amazing library. Though it crashes when wifi is off. down here is the crash trace. The problem may be in UdpTransport.kt class where you need to change :
Schedulers.io()).subscribe {s -> doStuff())
to:
Schedulers.io()).subscribe {s -> doStuff(),
    throwable -> Log.e(TAG, "Throwable " + throwable.getMessage()))

Helpful sources:
http://sangsoonam.github.io/2018/12/17/rxjava-onerrornotimplementedexception.html
https://softwareengineering.stackexchange.com/questions/376207/error-handling-best-practice-for-external-library

Thanks,
Yan

Here is the crash trace:
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.io.IOException: sendto failed: ENETUNREACH (Network is unreachable)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        W/System.err: Caused by: java.io.IOException: sendto failed: ENETUNREACH (Network is unreachable)
        at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:603)
        at libcore.io.IoBridge.sendto(IoBridge.java:571)
        at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:124)
        at java.net.DatagramSocket.send(DatagramSocket.java:721)
        at wo.lf.lifx.net.UdpTransport$messages$1$disposable$1.accept(UdpTransport.kt:79)
        at wo.lf.lifx.net.UdpTransport$messages$1$disposable$1.accept(UdpTransport.kt:59)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        W/System.err: 	... 9 more
        W/System.err: Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
        at libcore.io.Linux.sendtoBytes(Native Method)
        at libcore.io.Linux.sendto(Linux.java:227)
        at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:304)
        at libcore.io.IoBridge.sendto(IoBridge.java:569)
        W/System.err: 	... 14 more

**Comment by flowsprenger** [comment]
Thanks for reporting.
Please check if this is resolved in

`implementation 'wo.lf:rx-lifx:0.1.1-alpha'` 

for you, just terminating the send handler is not a good idea as that means no further message will be sent. Instead the whole transport is restarted, which with the default LightService will trigger a retry of the UdpTransport every two seconds

**Comment by YanMESS** [comment]
Many thanks Florian for the quick fix. It's not yet available on Jcenter() but that should be fine 👍

Greetings,
Yan

**Comment by flowsprenger** [comment]
Sorry Yan,

forgot that there is a publish button, the artifacts should now be available

**Comment by YanMESS** [comment]
Great, tested now and it didn't crash. Thanks again for this brilliant library.

Cheers,
Yan
